samba:
  container_name: samba
  image: phreakazoid/samba:latest
  restart: unless-stopped
  ports:
    - 137:137/udp
    - 138:138/udp
    - 139:139/tcp
    - 445:445/tcp
  volumes:
    - "/opt/kodi-headless-01:/config/.kodi"
  environment:
    - TZ="Europe/Berlin"
    - DOMAIN_NAME="localdomain.loc"
    - ADMIN_SERVER="dc1.localdomain.loc"
    - WORKGROUP="localdomain"
    - AD_USERNAME="Administrator"
    - AD_PASSWORD="V3rY1ns3cur3P4ssw0rd"
  extra_hosts:
    - "docker-smb.localdomain.loc docker-smb":<host ip address>
  tty: true  
